layout_spectrum: 0.07474291231483221
typography_spectrum: 0.6622127427253872
color:
  brandStrength: 0.5032892308663577
  lightness: 0.3321112496778369
  saturation: 0.037484249798581004
  rhythmicContrast: 0.7761984702665359
  brandColors:
    - '#F2385A'
    - '#F5A503'
    - '#E9F1DF'
    - '#4AD9D9'
    - '#36B1BF'
name: nathaliet trajes de baño
navigation:
  - name: Home
    url: 'http://thegrid.ai/nathaliet/'
    type: external
  - name: Poleras
    url: 'https://thegrid.ai/nathaliet-poleras/'
    type: external
