typography_spectrum: 0.8756823006551713
color:
  brandStrength: 0.9794230724219233
  lightness: 0.9799700165167451
  saturation: 0.0421843056101352
  rhythmicContrast: 0.6901399032212794
  brandColors:
    - '#FFF8E3'
    - '#CCCC9F'
    - '#33332D'
    - '#9FB4CC'
    - '#DB4105'
layout_spectrum: 0.06705787708051503
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/cc99a213-51df-4105-91b8-42a7d0384238.png
name: Nathaliet
navigation:
  - name: Home
    url: 'http://thegrid.ai/nathaliet/'
    type: external
  - name: Crop Tops
    url: 'https://thegrid.ai/nathaliet-croptops'
    type: external
  - name: Blazers
    url: 'https://thegrid.ai/nathaliet-blazers'
    type: external
  - name: Bodys
    url: 'https://thegrid.ai/nathaliet-body/'
    type: external
  - name: Vestidos
    url: 'https://thegrid.ai/nathaliet-vestidos'
    type: external
  - name: Trajes de Baño
    url: 'https://thegrid.ai/nathaliet-trajes-de-bano/'
    type: external
  - name: Agendar una cita
    url: 'http://m.me/nathalietme'
    type: external
  - name: Acerca de Nathaliet
    url: 'https://thegrid.ai/nathaliet/acerca-de-nathaliet/'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/1ffedf7f-b565-443f-a2b5-45fc9265669c.png
